import {
  Combine,
  Scissors,
  Minimize2,
  FileImage,
  ImageIcon,
  RotateCw,
  Droplets,
  Hash,
  Lock,
  Unlock,
  FileText,
  Stamp,
  FileOutput,
  Palette,
  ScanLine,
  Eraser,
} from "lucide-react";

const tools = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single document",
    icon: Combine,
    color: "bg-red-500",
    bgGradient: "bg-gradient-to-br from-red-400 to-red-600",
    category: "organize",
    multiple: true,
    accept: ".pdf",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Separate a PDF into individual pages",
    icon: Scissors,
    color: "bg-orange-500",
    bgGradient: "bg-gradient-to-br from-orange-400 to-orange-600",
    category: "organize",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size while maintaining quality",
    icon: Minimize2,
    color: "bg-green-500",
    bgGradient: "bg-gradient-to-br from-green-400 to-green-600",
    category: "optimize",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to JPG or PNG images",
    icon: FileImage,
    color: "bg-blue-500",
    bgGradient: "bg-gradient-to-br from-blue-400 to-blue-600",
    category: "convert",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert JPG, PNG images into a PDF document",
    icon: ImageIcon,
    color: "bg-purple-500",
    bgGradient: "bg-gradient-to-br from-purple-400 to-purple-600",
    category: "convert",
    multiple: true,
    accept: "image/*",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation",
    icon: RotateCw,
    color: "bg-teal-500",
    bgGradient: "bg-gradient-to-br from-teal-400 to-teal-600",
    category: "organize",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "watermark",
    name: "Add Watermark",
    description: "Stamp a text or image watermark on your PDF",
    icon: Droplets,
    color: "bg-cyan-500",
    bgGradient: "bg-gradient-to-br from-cyan-400 to-cyan-600",
    category: "edit",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to your PDF document",
    icon: Hash,
    color: "bg-indigo-500",
    bgGradient: "bg-gradient-to-br from-indigo-400 to-indigo-600",
    category: "edit",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt your PDF with a password",
    icon: Lock,
    color: "bg-rose-500",
    bgGradient: "bg-gradient-to-br from-rose-400 to-rose-600",
    category: "security",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF",
    icon: Unlock,
    color: "bg-amber-500",
    bgGradient: "bg-gradient-to-br from-amber-400 to-amber-600",
    category: "security",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "ocr",
    name: "OCR - Extract Text",
    description: "Extract text from scanned PDFs and images",
    icon: ScanLine,
    color: "bg-violet-500",
    bgGradient: "bg-gradient-to-br from-violet-400 to-violet-600",
    category: "convert",
    multiple: false,
    accept: ".pdf,image/*",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF documents to editable Word files",
    icon: FileText,
    color: "bg-sky-500",
    bgGradient: "bg-gradient-to-br from-sky-400 to-sky-600",
    category: "convert",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Add your signature to any PDF document",
    icon: Stamp,
    color: "bg-pink-500",
    bgGradient: "bg-gradient-to-br from-pink-400 to-pink-600",
    category: "edit",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "flatten",
    name: "Flatten PDF",
    description: "Flatten form fields and annotations",
    icon: FileOutput,
    color: "bg-lime-600",
    bgGradient: "bg-gradient-to-br from-lime-500 to-lime-700",
    category: "optimize",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "grayscale",
    name: "PDF to Grayscale",
    description: "Convert colorful PDFs to black and white",
    icon: Palette,
    color: "bg-gray-600",
    bgGradient: "bg-gradient-to-br from-gray-500 to-gray-700",
    category: "edit",
    multiple: false,
    accept: ".pdf",
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    description: "Delete specific pages from your PDF",
    icon: Eraser,
    color: "bg-red-600",
    bgGradient: "bg-gradient-to-br from-red-500 to-red-700",
    category: "organize",
    multiple: false,
    accept: ".pdf",
  },
];

export const categories = [
  { id: "all", name: "All Tools" },
  { id: "organize", name: "Organize" },
  { id: "convert", name: "Convert" },
  { id: "edit", name: "Edit" },
  { id: "optimize", name: "Optimize" },
  { id: "security", name: "Security" },
];

export default tools;